#1. 결측치  NaN 값

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [4]:
nan_deck = df['deck'].value_counts(dropna=False)
print(nan_deck)

NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: deck, dtype: int64


In [5]:
#누락 데이터를 찾음 : isnull
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [6]:
#not null 메서드로 데이터 찾기
print(df.notnull().sum())

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64


In [7]:
#누락 데이터를 찾음  
#print(df.isnull().sum(axis=0))
print(df.isnull().sum().sum())


869


In [8]:
missing_df = df.isnull()

In [9]:
for col in missing_df.columns:
    missing_count = missing_df[col].value_counts() 
    try:
        print(col, ': ', missing_count[True])
    except:
        print(col, ': ', 0)

survived :  0
pclass :  0
sex :  0
age :  177
sibsp :  0
parch :  0
fare :  0
embarked :  2
class :  0
who :  0
adult_male :  0
deck :  688
embark_town :  2
alive :  0
alone :  0


In [10]:
#NaN 값이 500개 이상인 열을 모두 삭제
df_thresh = df.dropna(axis=1, thresh=500)
print(df_thresh.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')


In [11]:
# age 열 나이 데이처가 없는 모든 행을 삭제 891 -177
df_age = df.dropna(subset=['age'], how='any', axis=0)
print(len(df_age))

714


In [14]:
#age 열의 첫 10개 데이터를 출력
print(df['age'].head(10))

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: age, dtype: float64


In [15]:
#age 열의 NaN 값을 평균으로 대체하기
mean_age = df['age'].mean(axis=0)
mean_age

29.69911764705882

In [16]:
df['age'].fillna(mean_age, inplace=True)  #fillna 로 NaN에 입력함

In [17]:
df['age'].head(10)

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: age, dtype: float64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          891 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [19]:
#embark_town 다른  값  넣기 829행
print(df['embark_town'][825:830])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
Name: embark_town, dtype: object


In [21]:
most_freq = df['embark_town'].value_counts (dropna=True). idxmax()
most_freq 

'Southampton'

In [23]:
df['embark_town'].fillna(most_freq, inplace=True)

In [25]:
#828번 직전데이터로 변경
df['embark_town'].fillna(method='ffill', inplace=True)
df['embark_town'] [825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
Name: embark_town, dtype: object

duplicate 중복

In [26]:
import pandas as pd
df = pd.DataFrame({'c1':["a","a","b", "a", "b"], 'c2':[1,1,1,2,2], 'c3' : [1,1,2,2,2]})

In [27]:
df #index 0과 1 같은 데이터

c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [33]:
df_dup=df.duplicated()

In [29]:
df_dup

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [30]:
col_dup=df['c2'].duplicated()
col_dup

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [31]:
df2 = df.drop_duplicates() #index 0과 1 같은 데이터
df2

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [32]:
df3 = df.drop_duplicates(subset=['c2','c3']) #컬럼c2 와 c3 같은 데이터
df3

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

conversion 값을 교체

In [34]:
df = pd.read_csv('./auto-mpg.csv', header=None)
df.columns = ['mpg','cylinders','displacement', 'horespower','weight', 'acceleration', 'model year', 'origin', 'name']

In [36]:
df.head(2)

mpg  cylinders  displacement horespower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [39]:
# mpg(mile per gallon) / kpi(kilometer per liter) 
# mpg to kpi -> 1.60934 / 3.78541
#1 mpg ->  0.425 kpi
mpg_to_kpi = 1.60934 / 3.78541

In [50]:
df['kpi'] = df['mpg'] * mpg_to_kpi

In [51]:
df.head(2)

mpg  cylinders  displacement horespower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   

   origin                       name       kpi  
0       1  chevrolet chevelle malibu  7.652571  
1       1          buick skylark 320  6.377143

In [52]:
df['kpi'] = df['kpi'].round(2)  #소수점 2자리 반올림

In [53]:
df.head(2)

mpg  cylinders  displacement horespower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   

   origin                       name   kpi  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38

In [54]:
df.dtypes #horse power object(데이터 중 '?' 섞임) ->  정수로 변경

mpg             float64
cylinders         int64
displacement    float64
horespower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpi             float64
dtype: object

In [56]:
df['horespower'].unique() #고유한 값을 확인 할 수 있음

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [59]:
len(df['horespower'].unique()) 

94

In [60]:
import numpy as np

In [61]:
# 누락 데이터 '?' 를 삭제
df['horespower'].replace('?', np.nan, inplace=True) 

In [62]:
df['horespower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', nan, '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [63]:
df.dropna(subset=['horespower'], axis=0, inplace=True) 

In [64]:
df['horespower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [65]:
len(df['horespower'].unique()) 

93

In [66]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horespower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpi             float64
dtype: object

In [67]:
df['horespower'] = df['horespower'].astype('float') #문자형 데이터를 실 수로 교체

In [71]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horespower      float64
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpi             float64
dtype: object

In [73]:
df['origin'].unique()

array([1, 3, 2])

In [77]:
df['origin'].replace(1, 'USA',inplace=True )  

In [78]:
df['origin'].unique()

array(['USA', 3, 2], dtype=object)

In [79]:
df['origin'].replace(2, 'EU',inplace=True )  
df['origin'].replace(3, 'JAPAN',inplace=True )  

In [80]:
df['origin'].unique()

array(['USA', 'JAPAN', 'EU'], dtype=object)

In [81]:
#df['origin'].replace({1:'USA', 2:'EU', 3:'JAPAN'},inplace=True)
print(df['origin'].unique())
print(df.dtypes)

['USA' 'JAPAN' 'EU']
mpg             float64
cylinders         int64
displacement    float64
horespower      float64
weight          float64
acceleration    float64
model year        int64
origin           object
name             object
kpi             float64
dtype: object


In [82]:
df['origin'] = df['origin'].astype('category') # 국적, 성별 , 사망여부 등 구분을 하기 위한 이산형 데이터니깐 category 로 바꿔줌 

In [83]:
print(df.dtypes)

mpg              float64
cylinders          int64
displacement     float64
horespower       float64
weight           float64
acceleration     float64
model year         int64
origin          category
name              object
kpi              float64
dtype: object


In [84]:
df['origin'] = df['origin'].astype('str')

In [85]:
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horespower      float64
weight          float64
acceleration    float64
model year        int64
origin           object
name             object
kpi             float64
dtype: object


In [110]:
print(df['model year'].unique())

[70, 71, 72, 73, 74, ..., 78, 79, 80, 81, 82]
Length: 13
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]


In [111]:
df['model year'] = df['model year'].astype('category') 

In [112]:
print(df.dtypes)

mpg              float64
cylinders          int64
displacement     float64
horespower       float64
weight           float64
acceleration     float64
model year      category
origin            object
name              object
kpi              float64
dtype: object


In [113]:
df['model year'].sample(3)

44    71
41    71
55    71
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

In [114]:
np.histogram(df['horespower'], bins=3)

(array([257, 103,  32]),
 array([ 46.        , 107.33333333, 168.66666667, 230.        ]))

In [115]:
count, bin_divers = np.histogram(df['horespower'], bins=3)

In [116]:
print(bin_divers)

[ 46.         107.33333333 168.66666667 230.        ]


In [ ]:
bin_names = ['저출력','보통출력','고출력']
df['hp_bin'] = pd.cut (x = df['horespower'], bins=bin_dividers, labels=bin_names, include_lowest=True) #데이터 배열 / 경계값 / bin 이름 라벨 / 

In [ ]:
print(df[['horespower', 'hp_bin']])

In [ ]:
horespower_dummies = pd.get_dummies(df['hp_bin'])

In [ ]:
print(horespower_dummies.head(10))